### ISSUE TITLE
csgo rcon controls not working

### ISSUE THREAD

**Issue by duckysuck** [dichternebel/daddel-bot#120]
Hi There,
I'm having trouble with rcon controls for !cs maps or !cs map . However quit seems to work fine.

**Comment by dichternebel** [comment]
Hi,
could go more into detail e.g. posting a screenshot or an error message?
`!cs maps` should list all available maps on the server. If that is not working, there might be an issue with the conntection to the server itself.
`!cs map` must be followed by the map name you want to switch to e.g. `!cs map de_mirage`

**Comment by dichternebel** [comment]
I just checked to bot features `maps` and `map` with a server running on version 1.38.3.7 and it works on my site. What do you get back when you call `!cs status` ?
